### ISSUE TITLE
unable to parse UV; error: failed to load mesh file: can't scan type: *main.UV

### ISSUE THREAD

**Issue by mewmew** [maxpoletaev/goxgl#2]
Trying to parse the `mesh.obj` file from [SESSION_1721684495_6916912_preview.zip](https://github.com/user-attachments/files/16340253/SESSION_1721684495_6916912_preview.zip) gives the following error:
```bash
$ ./goxgl SESSION_1721684495_6916912_preview/mesh.obj

failed to load mesh file: can't scan type: *main.UV
```

This is due to a runtime error when parsing the UV in `parseFace`.
```go
_, err = fmt.Sscanf(
	line, "f %d/%d %d/%d %d/%d",
	&v0, &face.UVs[0],
	&v1, &face.UVs[1],
	&v2, &face.UVs[2],
)
```

The `&face.UVs[0]` variable is of type `*UV`, while the sscanf `%d` verb expects an integer.

Mostly likely this is intended to use a field of the `UV` struct, and then use the verb `%f` to handle the float32 type of `UV.U` and `UV.V`.

**Comment by maxpoletaev** [comment]
Ah, I see. There's one case that I forgot to update, as I did not have a good OBJ file example where vertices don't include normal data. Fixed in https://github.com/maxpoletaev/goxgl/commit/8201bd7648823ece1a1a0ee8e9e16646b03bc837 Looks okay now, thanks for reporting!

<img width="912" alt="Screenshot 2024-07-23 at 15 39 28" src="https://github.com/user-attachments/assets/f822cdb7-5a79-424b-9150-6313a615054a">

**Comment by mewmew** [comment]
> Ah, I see. There's one case that I forgot to update, as I did not have a good OBJ file example where vertices don't include normal data. Fixed in https://github.com/maxpoletaev/goxgl/commit/8201bd7648823ece1a1a0ee8e9e16646b03bc837 Looks okay now, thanks for reporting!

Awesome! Thanks for the quick reply and fix @maxpoletaev!

I very much appreciate that you shared your repo with the open source community, it's a great learning reference for 3d rendering.

Joyous greetings,
Robin
